import { Audio } from "@remotion/media";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { fade } from "@remotion/transitions/fade";
import type React from "react";
import { Sequence, interpolate, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import {
  CHECK_FRAMES,
  COST_CARD_AT,
  DEMO_TYPING,
  FIX_AT,
  FLAG_AT,
  RECHECK_AT,
  SceneChart,
  SceneCost,
  SceneEditor,
  SceneEnd,
  SceneIntro,
  SceneReview,
  SceneRules,
  SceneTitle,
} from "./scenes";
import { C, FONT, clamp, useLayout } from "./theme";
import timeline from "./timeline.json";

const COMPONENTS: Record<string, React.FC> = {
  intro: SceneIntro,
  problem: SceneRules,
  review: SceneReview,
  title: SceneTitle,
  demo: SceneEditor,
  results: SceneChart,
  cost: SceneCost,
  end: SceneEnd,
};

export const SCENES = timeline.scenes.map((s) => ({ ...s, C: COMPONENTS[s.id] }));
export const T = timeline.transition; // transition overlap (frames)
export const TOTAL = SCENES.reduce((a, s) => a + s.d, 0) - T * (SCENES.length - 1);
const STARTS = SCENES.map((_, i) => SCENES.slice(0, i).reduce((a, s) => a + s.d, 0) - i * T);
const START: Record<string, number> = Object.fromEntries(SCENES.map((s, i) => [s.id, STARTS[i]]));
const STORY = SCENES.filter((s) => s.id !== "intro").length; // the counter ignores the opening card

// Frame chrome: corner marks, label, scene counter, progress bar.
const Chrome: React.FC = () => {
  const frame = useCurrentFrame();
  const { durationInFrames, width, height } = useVideoConfig();
  const { square } = useLayout();
  const idx = STARTS.reduce((a, s, i) => (frame >= s + T / 2 ? i : a), 0);
  const inset = square ? 32 : 44;
  const arm = 22;
  const corner = (x: number, y: number, sx: number, sy: number) => (
    <div
      key={`${x}${y}`}
      style={{
        position: "absolute",
        left: x,
        top: y,
        width: arm,
        height: arm,
        borderLeft: sx > 0 ? `2px solid ${C.faint}` : undefined,
        borderRight: sx < 0 ? `2px solid ${C.faint}` : undefined,
        borderTop: sy > 0 ? `2px solid ${C.faint}` : undefined,
        borderBottom: sy < 0 ? `2px solid ${C.faint}` : undefined,
      }}
    />
  );
  const prog = interpolate(frame, [0, durationInFrames - 1], [0, 1], clamp);
  const showLabels = !["intro", "title", "end"].includes(SCENES[idx].id);
  return (
    <div style={{ position: "absolute", inset: 0, fontFamily: FONT, pointerEvents: "none" }}>
      {corner(inset, inset, 1, 1)}
      {corner(width - inset - arm, inset, -1, 1)}
      {corner(inset, height - inset - arm, 1, -1)}
      {corner(width - inset - arm, height - inset - arm, -1, -1)}
      <div style={{ position: "absolute", top: inset + 30, left: inset + 30, fontSize: 18, color: C.dim, letterSpacing: "0.08em", opacity: showLabels ? 1 : 0 }}>JEV-LINT</div>
      <div style={{ position: "absolute", top: inset + 30, right: inset + 30, fontSize: 18, color: C.dim, letterSpacing: "0.08em", opacity: showLabels ? 1 : 0 }}>
        {String(idx).padStart(2, "0")} / {String(STORY).padStart(2, "0")}
      </div>
      <div style={{ position: "absolute", left: inset + 30, right: inset + 30, bottom: inset + 8, height: 2, background: C.line }}>
        <div style={{ height: 2, width: `${prog * 100}%`, background: C.dim }} />
      </div>
    </div>
  );
};

/* ───────────── Sound: generated by audio/generate.py, placed on the same timeline ───────────── */
type Cue = { at: number; src: string; vol: number; len?: number };

const typingCues = (start: number, bursts: readonly (readonly [number, number])[], cps: number, fps: number): Cue[] =>
  bursts.map(([at, chars]) => ({ at: start + at, src: "typing", vol: 0.32, len: Math.max(4, Math.ceil((chars / cps) * fps)) }));

const buildCues = (fps: number): Cue[] => {
  const s = START;
  return [
    // Scene transitions
    ...STARTS.slice(1).map((st) => ({ at: st - 4, src: "whoosh", vol: 0.22 })),
    // 1. rules typed as comments (48 chars/s)
    ...typingCues(s.problem, [
      [34, 38],
      [54, 30],
      [74, 35],
    ], 48, fps),
    // 2. review nodes pop; extra round trip turns red
    ...[0, 1, 2, 3].map((i) => ({ at: s.review + 16 + i * 9 + 4, src: "pop", vol: 0.16 })),
    { at: s.review + 62, src: "thunk", vol: 0.28 },
    // 3. title typed (20 chars/s)
    ...typingCues(s.title, [[2, 8]], 20, fps),
    // 4. demo: agent types, hook flags (red), agent fixes, hook passes (green)
    ...typingCues(s.demo, DEMO_TYPING, 42, fps),
    { at: s.demo + FLAG_AT, src: "pop", vol: 0.12 },
    { at: s.demo + FLAG_AT + CHECK_FRAMES, src: "thunk", vol: 0.5 },
    { at: s.demo + FIX_AT, src: "pop", vol: 0.12 },
    { at: s.demo + RECHECK_AT, src: "pop", vol: 0.1 },
    { at: s.demo + RECHECK_AT + CHECK_FRAMES, src: "chime", vol: 0.42 },
    // 5. chart bars land
    ...[46, 56, 72, 82].map((f) => ({ at: s.results + f, src: "pop", vol: 0.2 })),
    // 6. cost cards land
    ...COST_CARD_AT.map((f) => ({ at: s.cost + f + 4, src: "pop", vol: 0.2 })),
  ];
};

const SoundTrack: React.FC = () => {
  const { fps } = useVideoConfig();
  const cues = buildCues(fps);
  // Duck the music under the prominent SFX (thunk, chime) and, lightly, under typing.
  const duck = (f: number) => {
    let g = 1;
    for (const c of cues) {
      if (c.src === "thunk" || c.src === "chime") {
        g = Math.min(g, interpolate(f, [c.at - 3, c.at, c.at + 20, c.at + 40], [1, 0.45, 0.45, 1], clamp));
      } else if (c.src === "typing" && c.len) {
        g = Math.min(g, interpolate(f, [c.at - 3, c.at, c.at + c.len, c.at + c.len + 8], [1, 0.75, 0.75, 1], clamp));
      }
    }
    return g;
  };
  return (
    <>
      <Audio src={staticFile("audio/music.wav")} volume={(f) => 0.9 * duck(f)} />
      {cues.map((c, i) => (
        <Sequence key={`${c.src}-${i}`} from={Math.max(0, c.at)} durationInFrames={c.len ?? 2 * fps} layout="none">
          <Audio src={staticFile(`audio/${c.src}.wav`)} volume={c.vol} trimBefore={c.src === "typing" ? (i * 17) % 200 : undefined} />
        </Sequence>
      ))}
    </>
  );
};

export const JevLintVideo: React.FC = () => (
  <div style={{ position: "absolute", inset: 0, background: C.bg }}>
    <TransitionSeries>
      {SCENES.flatMap((s, i) => {
        const seq = (
          <TransitionSeries.Sequence key={s.id} durationInFrames={s.d} premountFor={30}>
            <s.C />
          </TransitionSeries.Sequence>
        );
        return i === 0 ? [seq] : [<TransitionSeries.Transition key={`t${s.id}`} presentation={fade()} timing={linearTiming({ durationInFrames: T })} />, seq];
      })}
    </TransitionSeries>
    <Chrome />
    <SoundTrack />
  </div>
);
