// Repo-local rule packs: the nearest `.jev-lint/` directory above an edited file.
//
//   .jev-lint/
//     config.json          optional: { "packs": ["repo", "practices"] } picks packs for this repo
//     <name>.rules.json    same shape as rules/*.json: { language, extensions, rules: [...] }
//     cases.jsonl          optional labeled examples, used by `bun src/validate.ts`
//
// Generated by the jev-lint-rules skill from the repo's own coding guidelines.

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, parse } from "node:path";
import type { Rule, RuleSet } from "./lint";

export type RepoConfig = { dir: string; packs?: string[]; ruleSets: RuleSet[] };

const cache = new Map<string, RepoConfig | null>();

function isRule(value: unknown): value is Rule {
  const r = value as Rule;
  return Boolean(
    r && typeof r.id === "string" && typeof r.question === "string" && typeof r.true === "string" && typeof r.false === "string",
  );
}

export function loadRepoDir(dir: string): RepoConfig {
  const ruleSets: RuleSet[] = [];
  for (const name of readdirSync(dir)
    .filter((n) => n.endsWith(".rules.json"))
    .sort()) {
    try {
      const parsed = JSON.parse(readFileSync(join(dir, name), "utf8")) as Partial<RuleSet>;
      if (typeof parsed.language !== "string" || !Array.isArray(parsed.extensions) || !Array.isArray(parsed.rules)) continue;
      const rules = parsed.rules.filter(isRule).map((r) => ({ ...r, fix: r.fix ?? "" }));
      ruleSets.push({ language: parsed.language, extensions: parsed.extensions.map((e) => e.toLowerCase()), rules });
    } catch {
      // A malformed repo file must never break the hook; skip it.
    }
  }
  let packs: string[] | undefined;
  try {
    const config = JSON.parse(readFileSync(join(dir, "config.json"), "utf8")) as { packs?: unknown };
    if (Array.isArray(config.packs)) packs = config.packs.filter((p): p is string => typeof p === "string");
  } catch {
    // config.json is optional
  }
  return { dir, packs, ruleSets };
}

// Walks up from the file's directory to the filesystem root.
export function findRepoConfig(absoluteFilePath: string): RepoConfig | undefined {
  const visited: string[] = [];
  let dir = dirname(absoluteFilePath);
  const { root } = parse(dir);
  let found: RepoConfig | null = null;
  for (;;) {
    const cached = cache.get(dir);
    if (cached !== undefined) {
      found = cached;
      break;
    }
    visited.push(dir);
    const candidate = join(dir, ".jev-lint");
    if (existsSync(candidate)) {
      found = loadRepoDir(candidate);
      break;
    }
    if (dir === root) break;
    dir = dirname(dir);
  }
  for (const v of visited) cache.set(v, found);
  return found ?? undefined;
}
